# Green Computing Project, Academic Year 2025/26

Student: Vavassori Alessandra

Student ID: 942819

Student e-mail adress: a.vavassori11@campus.unimib.it

**Introduction**

For the development of this project, it was chosen to apply Random Forest algorithm on all five datasets. For each dataset, several pre-processing operations were performed, such as checking missing values, analyzing the target distribution and making some adjustments in case of unusual variable values.

After the pre-processing step, it was implemented a "standard" version of the code on each dataset in order to evaluate the result of Matthews Correlation Coefficient (MCC), energy consumption, execution time (in seconds) and CO2 emissions.

Subsequently, a "green" version of the code was developed by applying specific strategies to reduce all the consumption values while maintaining a good performance.

In [ ]:
#importing libraries

!pip install codecarbon
import pandas as pd
import numpy as np
import time

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import matthews_corrcoef, confusion_matrix
from sklearn.model_selection import train_test_split

from codecarbon import EmissionsTracker

Requirement already satisfied: codecarbon in /usr/local/lib/python3.12/dist-packages (3.2.8)
Requirement already satisfied: arrow in /usr/local/lib/python3.12/dist-packages (from codecarbon) (1.4.0)
Requirement already satisfied: authlib>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from codecarbon) (1.7.2)
Requirement already satisfied: joserfc>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from codecarbon) (1.7.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from codecarbon) (8.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from codecarbon) (2.2.2)
Requirement already satisfied: prometheus_client in /usr/local/lib/python3.12/dist-packages (from codecarbon) (0.25.0)
Requirement already satisfied: psutil>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from codecarbon) (7.2.2)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from codecarbon) (9.0.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from codecarbon) (2.12.3)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from codecarbon) (13.610.43)
Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.12/dist-packages (from codecarbon) (3.14.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from codecarbon) (2.32.4)
Requirement already satisfied: questionary in /usr/local/lib/python3.12/dist-packages (from codecarbon) (2.1.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from codecarbon) (13.9.4)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from codecarbon) (0.25.1)
Requirement already satisfied: pycountry in /usr/local/lib/python3.12/dist-packages (from codecarbon) (26.2.16)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from authlib>=1.2.1->codecarbon) (48.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->codecarbon) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->codecarbon) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->codecarbon) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->codecarbon) (0.4.2)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from arrow->codecarbon) (2.9.0.post0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from arrow->codecarbon) (2026.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->codecarbon) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->codecarbon) (2025.2)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from questionary->codecarbon) (3.0.52)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->codecarbon) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->codecarbon) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->codecarbon) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->codecarbon) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->codecarbon) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->codecarbon) (2.20.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->codecarbon) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->codecarbon) (0.0.4)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography->authlib>=1.2.1->codecarbon) (2.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->codecarbon) (0.1.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt_toolkit<4.0,>=2.0->questionary->codecarbon) (0.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->arrow->codecarbon) (1.17.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography->authlib>=1.2.1->codecarbon) (3.0)

# First dataset: Neuroblastoma

In [ ]:
df_neuroblastoma = pd.read_csv("/content/data_neuroblastoma.csv")
df_neuroblastoma

,age,sex,site,stage,risk,time_months,autologous_stem_cell_transplantation,radiation,degree_of_differentiation,UH_or_FH,MYCN_status,surgical_methods,outcome
0,2,0,0,1,1,7.0,0,0,0,0,1,1,0
1,2,0,0,1,1,19.0,0,1,0,0,1,1,1
2,1,0,0,1,1,25.0,0,1,1,0,1,0,1
3,1,0,0,1,1,8.0,0,0,1,0,1,1,0
4,1,0,0,1,1,47.0,1,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,0,0,0,0,0,36.0,0,0,0,0,1,0,0
165,1,0,0,0,0,18.0,0,0,1,1,1,1,1
166,1,1,1,0,0,38.0,0,0,2,1,1,0,0
167,1,1,1,0,0,37.0,0,0,1,1,1,0,0
168,0,0,0,0,0,32.0,0,0,0,0,1,0,0

In [ ]:
#Pre-processing

#number of rows and columns
print(f"Shape dataset:\n {df_neuroblastoma.shape}")

#variable types
print(f"Data types:\n {df_neuroblastoma.dtypes}")

#summary statistics
print(f"Summary statistics:\n {df_neuroblastoma.describe()}")

#distribution of the target variable
print(f"Distribution of the target:\n {df_neuroblastoma['outcome'].value_counts()}")

#missing values
print(f"Missing values per column:\n {df_neuroblastoma.isnull().sum()}")

#one-hot encoding for the categorical variable 'site'
df_neuroblastoma = pd.get_dummies(df_neuroblastoma, columns=['site'], dtype=int)
df_neuroblastoma

Shape dataset:
 (169, 13)
Data types:
 age                                       int64
sex                                       int64
site                                      int64
stage                                     int64
risk                                      int64
time_months                             float64
autologous_stem_cell_transplantation      int64
radiation                                 int64
degree_of_differentiation                 int64
UH_or_FH                                  int64
MYCN_status                               int64
surgical_methods                          int64
outcome                                   int64
dtype: object
Summary statistics:
               age         sex        site       stage        risk  \
count  169.000000  169.000000  169.000000  169.000000  169.000000
mean     1.124260    0.349112    0.213018    0.686391    0.810651
std      0.628635    0.478106    0.525149    0.465338    0.392950
min      0.000000    0.000000    0.000000    0.000000    0.000000
25%      1.000000    0.000000    0.000000    0.000000    1.000000
50%      1.000000    0.000000    0.000000    1.000000    1.000000
75%      2.000000    1.000000    0.000000    1.000000    1.000000
max      2.000000    1.000000    2.000000    1.000000    1.000000

       time_months  autologous_stem_cell_transplantation   radiation  \
count   169.000000                             169.00000  169.000000
mean     36.180473                               0.08284    0.644970
std      23.035137                               0.27646    0.479944
min       1.000000                               0.00000    0.000000
25%      15.000000                               0.00000    0.000000
50%      34.000000                               0.00000    1.000000
75%      53.000000                               0.00000    1.000000
max     100.000000                               1.00000    1.000000

       degree_of_differentiation    UH_or_FH  MYCN_status   surgical_methods  \
count                 169.000000  169.000000    169.000000        169.000000
mean                    0.662722    0.195266      0.733728          0.343195
std                     0.576190    0.397584      0.443322          0.476187
min                     0.000000    0.000000      0.000000          0.000000
25%                     0.000000    0.000000      0.000000          0.000000
50%                     1.000000    0.000000      1.000000          0.000000
75%                     1.000000    0.000000      1.000000          1.000000
max                     2.000000    1.000000      1.000000          1.000000

          outcome
count  169.000000
mean     0.455621
std      0.499507
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      1.000000
Distribution of the target:
 outcome
0    92
1    77
Name: count, dtype: int64
Missing values per column:
 age                                     0
sex                                     0
site                                    0
stage                                   0
risk                                    0
time_months                             0
autologous_stem_cell_transplantation    0
radiation                               0
degree_of_differentiation               0
UH_or_FH                                0
MYCN_status                             0
surgical_methods                        0
outcome                                 0
dtype: int64

,age,sex,stage,risk,time_months,autologous_stem_cell_transplantation,radiation,degree_of_differentiation,UH_or_FH,MYCN_status,surgical_methods,outcome,site_0,site_1,site_2
0,2,0,1,1,7.0,0,0,0,0,1,1,0,1,0,0
1,2,0,1,1,19.0,0,1,0,0,1,1,1,1,0,0
2,1,0,1,1,25.0,0,1,1,0,1,0,1,1,0,0
3,1,0,1,1,8.0,0,0,1,0,1,1,0,1,0,0
4,1,0,1,1,47.0,1,1,1,0,1,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,0,0,0,0,36.0,0,0,0,0,1,0,0,1,0,0
165,1,0,0,0,18.0,0,0,1,1,1,1,1,1,0,0
166,1,1,0,0,38.0,0,0,2,1,1,0,0,0,1,0
167,1,1,0,0,37.0,0,0,1,1,1,0,0,0,1,0
168,0,0,0,0,32.0,0,0,0,0,1,0,0,1,0,0

In [ ]:
#Standard code

X = df_neuroblastoma.drop(columns=['outcome'])
y = df_neuroblastoma['outcome']

np.random.seed(42)

mcc_vector = []

tracker_standard = EmissionsTracker(
    log_level="error",
    save_to_file=False
)

tracker_standard.start()
start_time_standard = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_standard = RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        class_weight='balanced',
        random_state=42
    )

    rf_standard.fit(
        X_train,
        y_train
    )

    y_pred_standard = rf_standard.predict(X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_standard
    )

    mcc_vector.append(mcc)

end_time_standard = time.time()

execution_time_standard = (end_time_standard - start_time_standard)

emissions_standard = tracker_standard.stop() * 1000

energy_standard_wh = (tracker_standard._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.29f}")
print(f"Energy: {energy_standard_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_standard:.20f} CO2 eq grams")
print(f"Execution time: {execution_time_standard:.20f} seconds")

The final results are:
Mean MCC: 0.44417242142400198412
Median MCC: 0.44565217391304345895
Standard deviation MCC: 0.10814807511483337521
Minimum MCC: 0.15521549593647762655
Maximum MCC: 0.72481421078251084821886252030
Energy: 0.06633140248406961537 Wh
CO2 emissions: 0.01893786337351972826 CO2 eq grams
Execution time: 17.66194319725036621094 seconds

In [ ]:
#Green code

X = df_neuroblastoma.drop(columns=['outcome'])
y = df_neuroblastoma['outcome']

np.random.seed(42)

mcc_vector = []

tracker_green = EmissionsTracker(
    log_level="error",
    save_to_file=False
)

tracker_green.start()

start_time_green = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_green = RandomForestClassifier(
        n_estimators=20,
        max_depth=5,
        min_samples_leaf=3,
        class_weight='balanced',
        random_state=42
    )

    rf_green.fit(
        X_train,
        y_train
    )

    y_pred_green = rf_green.predict(
        X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_green
    )

    mcc_vector.append(mcc)

end_time_green = time.time()

execution_time_green = (
    end_time_green - start_time_green)

emissions_green = tracker_green.stop() * 1000

energy_green_wh = (tracker_green._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_green_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_green:.20f} CO2 eq grams")
print(f"Execution time: {execution_time_green:.20f} seconds")

The final results are:
Mean MCC: 0.51370486388612301987
Median MCC: 0.52279451819237399146
Standard deviation MCC: 0.10597273695077616407
Minimum MCC: 0.24493247972574661020
Maximum MCC: 0.72481421078251084822

Energy: 0.01667962261167760946 Wh
CO2 emissions: 0.00476209460847270422 CO2 eq grams
Execution time: 4.25146222114562988281 seconds

Exclusively on the first dataset it was applied another green strategy which consisted in feature selection based on the ranking of important features and selecting only the first ten (k=10).

However, it was noticed that the results collected through this strategy for energy consumptions, emissions and execution time were actually worse compared to the ones obtained with the strategy based solely on hyperparameter modification.
Consequently, this strategy was discarded and for the remaining datasets it was applied only the modification of hyperparameters.

Further details and explanation are provided in the section of the report entitled “4.2 Evaluation of an additional strategy: Feature Selection".

In [ ]:
#Optional strategy applied only on the first dataset: Feature Selection based on importance ranking

X = df_neuroblastoma.drop(columns=['outcome'])
y = df_neuroblastoma['outcome']

np.random.seed(42)

mcc_vector = []

#number of features kept
k = 10

tracker_green = EmissionsTracker(
    log_level="error",
    save_to_file=False
)

tracker_green.start()

start_time_green = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Feature selection only on the training set
    rf_selector = RandomForestClassifier(
        n_estimators=100,
        random_state=42
    )
    rf_selector.fit(X_train, y_train)

    #ranking of features according to importance
    feature_importances = rf_selector.feature_importances_

    #select top 10 features
    top_k_indices = np.argsort(feature_importances)[::-1][:k]
    selected_features = X_train.columns[top_k_indices]

    X_train_selected = X_train[selected_features]
    X_test_selected = X_test[selected_features]

    #Random Forest
    rf_green = RandomForestClassifier(
        n_estimators=20,
        max_depth=5,
        min_samples_leaf=3,
        class_weight='balanced',
        random_state=42
    )

    rf_green.fit(
        X_train_selected,
        y_train)

    y_pred_green = rf_green.predict(
        X_test_selected)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_green
    )

    mcc_vector.append(mcc)

end_time_green = time.time()

execution_time_green = (end_time_green - start_time_green)

emissions_green = tracker_green.stop() * 1000

energy_green_wh = (tracker_green._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_green_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_green:.20f} CO2 eq grams")
print(f"Execution time: {execution_time_green:.20f} seconds")

The final results are:
Mean MCC: 0.53147481778833993715
Median MCC: 0.52712951122173978824
Standard deviation MCC: 0.10538781186965831549
Minimum MCC: 0.24371482196617177962
Maximum MCC: 0.76242236024844722841

Energy: 0.08088701595892311413 Wh
CO2 emissions: 0.02309354543332149332 CO2 eq grams
Execution time: 21.62535667419433593750 seconds

# Second dataset: Pediatric brain tumor

In [ ]:
df_pediatric = pd.read_csv("/content/dataset_Belgrade2021_pediatric_brain_tumor.csv")

In [ ]:
#Pre-processing

#number of rows and columns
print(f"Shape dataset:\n {df_pediatric.shape}")

#variable types
print(f"Data types:\n {df_pediatric.dtypes}")

#summary statistics
print(f"Summary statistics:\n {df_pediatric.describe()}")

#distribution of target variable
print(f"Distribuzione target:\n {df_pediatric['Status OS'].value_counts()}")

#missing values
print(f"Missing values per column:\n {df_pediatric.isnull().sum()}")

#one-hot encoding for the categorical variable 'operation type'
df_pediatric = pd.get_dummies(df_pediatric, columns=['Operation type'], dtype=int)
df_pediatric

Shape dataset:
 (173, 31)
Data types:
 Sex                                                int64
Age                                                int64
Duration of sympthoms before diagnosis (days)    float64
Increased ICP                                      int64
Epileptic seizures                                 int64
Neurological deficit                               int64
Hormonal abnormalities                             int64
Operation type                                     int64
Localisation                                     float64
Embryonal tumors                                   int64
HGG                                                int64
LGG                                                int64
Craniopharyngeoma                                  int64
GCT / NGCT                                         int64
Ependymoma                                         int64
Glioneural Tu                                      int64
Pineal Tu                                          int64
Choroid plexus Tu                                  int64
Other                                              int64
Unknown                                            int64
MRI finding                                        int64
CSF cytology                                       int64
Extent of disease                                  int64
Neoadjuvant HT                                     int64
Radiotherapy                                     float64
CSI dose                                         float64
Total dose                                       float64
Concomitant HT                                   float64
Adjuvant HT                                        int64
OS                                               float64
Status OS                                          int64
dtype: object
Summary statistics:
               Sex          Age  Duration of sympthoms before diagnosis (days)  \
count  173.000000   173.000000                                     173.000000
mean     1.479769  2002.375723                                      96.071676
std      0.501041     5.239928                                     126.660996
min      1.000000  1992.000000                                      11.600000
25%      1.000000  1999.000000                                      27.000000
50%      1.000000  2002.000000                                      48.000000
75%      2.000000  2006.000000                                      91.000000
max      2.000000  2011.000000                                     499.000000

       Increased ICP  Epileptic seizures  Neurological deficit  \
count     173.000000          173.000000            173.000000
mean        1.260116            1.861272              1.381503
std         0.439971            0.346666              0.487166
min         1.000000            1.000000              1.000000
25%         1.000000            2.000000              1.000000
50%         1.000000            2.000000              1.000000
75%         2.000000            2.000000              2.000000
max         2.000000            2.000000              2.000000

       Hormonal abnormalities  Operation type  Localisation  Embryonal tumors  \
count              173.000000      173.000000    173.000000        173.000000
mean                 1.890173        3.046243      1.610405          1.624277
std                  0.313581        0.888002      0.518166          0.485715
min                  1.000000        1.000000      1.000000          1.000000
25%                  2.000000        2.000000      1.000000          1.000000
50%                  2.000000        3.000000      2.000000          2.000000
75%                  2.000000        4.000000      2.000000          2.000000
max                  2.000000        4.000000      2.400000          2.000000

       ...  CSF cytology  Extent of disease  Neoadjuvant HT  Radiotherapy  \
count  ...    173.000000         173.000000      173.000000    173.000000
mean   ...      1.566474           1.757225        1.809249      1.020809
std    ...      0.497000           0.599435        0.394034      0.089087
min    ...      1.000000           1.000000        1.000000      1.000000
25%    ...      1.000000           1.000000        2.000000      1.000000
50%    ...      2.000000           2.000000        2.000000      1.000000
75%    ...      2.000000           2.000000        2.000000      1.000000
max    ...      2.000000           3.000000        2.000000      1.400000

         CSI dose  Total dose  Concomitant HT  Adjuvant HT          OS  \
count  173.000000  173.000000      173.000000   173.000000  173.000000
mean    30.439827   53.805723        1.979191     1.462428   64.604624
std      3.199297    1.631373        0.089087     0.500034   47.478318
min     24.000000   50.320000        1.600000     1.000000    6.000000
25%     30.600000   54.000000        2.000000     1.000000   16.000000
50%     30.600000   54.000000        2.000000     1.000000   57.000000
75%     30.600000   54.800000        2.000000     2.000000  104.000000
max     35.200000   55.800000        2.000000     2.000000  147.400000

        Status OS
count  173.000000
mean     1.543353
std      0.499563
min      1.000000
25%      1.000000
50%      2.000000
75%      2.000000
max      2.000000

[8 rows x 31 columns]
Distribuzione target:
 Status OS
2    94
1    79
Name: count, dtype: int64
Missing values per column:
 Sex                                              0
Age                                              0
Duration of sympthoms before diagnosis (days)    0
Increased ICP                                    0
Epileptic seizures                               0
Neurological deficit                             0
Hormonal abnormalities                           0
Operation type                                   0
Localisation                                     0
Embryonal tumors                                 0
HGG                                              0
LGG                                              0
Craniopharyngeoma                                0
GCT / NGCT                                       0
Ependymoma                                       0
Glioneural Tu                                    0
Pineal Tu                                        0
Choroid plexus Tu                                0
Other                                            0
Unknown                                          0
MRI finding                                      0
CSF cytology                                     0
Extent of disease                                0
Neoadjuvant HT                                   0
Radiotherapy                                     0
CSI dose                                         0
Total dose                                       0
Concomitant HT                                   0
Adjuvant HT                                      0
OS                                               0
Status OS                                        0
dtype: int64

,Sex,Age,Duration of sympthoms before diagnosis (days),Increased ICP,Epileptic seizures,Neurological deficit,Hormonal abnormalities,Localisation,Embryonal tumors,HGG,...,CSI dose,Total dose,Concomitant HT,Adjuvant HT,OS,Status OS,Operation type_1,Operation type_2,Operation type_3,Operation type_4
0,1,1996,36.0,1,2,1,2,2.0,2,2,...,30.6,54.00,2.0,2,147.4,2,0,1,0,0
1,1,1996,21.0,1,2,1,2,2.0,1,2,...,35.2,55.25,2.0,2,19.0,1,0,0,0,1
2,2,2001,30.0,2,2,1,2,2.0,2,2,...,30.6,50.32,2.0,2,6.0,1,0,0,1,0
3,2,2001,365.0,2,2,1,1,1.0,2,2,...,30.6,54.00,2.0,2,147.4,2,0,0,1,0
4,1,1993,33.0,1,2,2,2,1.0,2,2,...,30.6,55.80,2.0,2,146.0,2,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,1,2006,14.0,1,1,2,2,1.0,2,2,...,34.2,55.80,2.0,1,24.0,1,0,0,1,0
169,1,2009,20.0,1,2,2,2,1.0,2,1,...,30.6,55.80,1.6,1,17.0,1,0,0,0,1
170,2,2008,14.0,1,2,1,2,2.0,1,2,...,34.2,54.00,2.0,1,14.0,1,0,0,0,1
171,1,2011,11.6,2,2,1,2,2.0,1,2,...,30.6,50.32,2.0,2,6.0,1,0,0,1,0
172,2,2009,118.0,1,2,2,2,2.0,1,2,...,30.6,54.00,2.0,2,6.0,1,0,1,0,0

In [ ]:
#Standard code

X = df_pediatric.drop(columns=['Status OS'])
y = df_pediatric['Status OS']

np.random.seed(42)

mcc_vector = []

tracker_standard = EmissionsTracker(
    log_level="error",
    save_to_file=False
)

tracker_standard.start()

start_time_standard = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_standard = RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        class_weight='balanced',
        random_state=42
    )

    rf_standard.fit(
        X_train,
        y_train
    )

    y_pred_standard = rf_standard.predict(
        X_test
    )

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_standard
    )

    mcc_vector.append(mcc)

end_time_standard = time.time()

execution_time_standard = (end_time_standard - start_time_standard)

emissions_standard = tracker_standard.stop() * 1000

energy_standard_wh = (tracker_standard._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_standard_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_standard:.20f} CO2 eq grams")
print(f"Execution time: {execution_time_standard:.20f} seconds")

The final results are:
Mean MCC: 0.77821204511927877245
Median MCC: 0.77462068290289820549
Standard deviation MCC: 0.07959529593802183722
Minimum MCC: 0.41903519109970349676
Maximum MCC: 0.92496246170077389692

Energy: 0.13032101473726587226 Wh
CO2 emissions: 0.03720713688189415669 CO2 eq grams
Execution time: 28.56003522872924804688 seconds

In [ ]:
#Green code

X = df_pediatric.drop(columns=['Status OS'])
y = df_pediatric['Status OS']

np.random.seed(42)

mcc_vector = []

tracker_green = EmissionsTracker(
    log_level="error",
    save_to_file=False
)

tracker_green.start()

start_time_green = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_green = RandomForestClassifier(
        n_estimators=20,
        max_depth=5,
        min_samples_leaf=3,
        class_weight='balanced',
        random_state=42
    )

    rf_green.fit(
        X_train,
        y_train
    )

    y_pred_green = rf_green.predict(
        X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_green
    )

    mcc_vector.append(mcc)

end_time_green = time.time()

execution_time_green = (end_time_green - start_time_green)

emissions_green = tracker_green.stop() * 1000

energy_green_wh = (tracker_green._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_green_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_green:.20f} CO2 eq grams")
print(f"Execution time: {execution_time_green:.20f} seconds")

The final results are:
Mean MCC: 0.79982218333099242003
Median MCC: 0.80657769207694995917
Standard deviation MCC: 0.06722511677993665835
Minimum MCC: 0.60258274378375875635
Maximum MCC: 0.92582009977255153022

Energy: 0.01510871247315800393 Wh
CO2 emissions: 0.00431359389144797458 CO2 eq grams
Execution time: 3.63488578796386718750 seconds

# Third Dataset: Colorectal cancer

In [ ]:
df_colcancer=pd.read_csv("/content/dataset_Taipei2018_colorectal_cancer.csv")
df_colcancer

,bian_ma,age,gender,asa,asa3,dm,cad,hf,cva,ckd,...,signet_ring,lymphovascularinvasion,perineural,ct,rt,nactrt,interval,progress,interval_r,death
0,2,52,1,3,1,0,0,0,0,0,...,0,1,0,1,0,0,11.761807,1,9.856263,1
1,21,85,2,2,0,0,1,0,0,0,...,0,0,0,1,0,0,8.377823,1,7.063655,1
2,22,45,2,2,0,0,0,0,0,0,...,0,1,0,1,0,0,4.763860,1,2.792608,1
3,23,57,2,2,0,0,0,0,0,0,...,0,1,0,1,0,0,2.595483,1,1.774127,1
4,29,43,1,2,0,1,0,0,0,0,...,0,0,0,1,0,0,16.164271,1,7.096509,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,5158,48,1,3,1,0,0,0,0,0,...,0,0,0,1,0,0,18.398357,0,18.398357,0
995,5162,86,1,3,1,0,0,0,0,0,...,0,0,0,0,0,1,17.478439,1,8.410678,0
996,5168,49,2,2,0,0,0,0,0,0,...,0,1,1,0,0,0,0.131417,0,0.131417,0
997,5171,76,2,2,0,1,0,0,0,0,...,0,1,1,1,0,0,20.008214,1,16.558522,0
998,5172,65,1,2,0,0,0,0,0,0,...,0,1,0,1,0,0,19.909651,1,3.909651,0

In [ ]:
#variables inspection
df_colcancer.columns

df_colcancer["asa"].value_counts()
df_colcancer["cea"].value_counts()
df_colcancer["log_cea"].value_counts()

#dropping the variable
df_colcancer.drop('cea', axis=1, inplace=True)

#next variables give values: 0, 1, 9
print(df_colcancer["cva"].value_counts())
print(df_colcancer["cell_diff"].value_counts())
print(df_colcancer["mucin_type"].value_counts())
print(df_colcancer["signet_ring"].value_counts())
print(df_colcancer["lymphovascularinvasion"].value_counts())
print(df_colcancer["perineural"].value_counts())

cva
0    942
1     57
Name: count, dtype: int64
cell_diff
1    813
2    121
9     65
Name: count, dtype: int64
mucin_type
0    869
1     73
9     57
Name: count, dtype: int64
signet_ring
0    900
9     57
1     42
Name: count, dtype: int64
lymphovascularinvasion
1    485
0    460
9     54
Name: count, dtype: int64
perineural
0    734
1    208
9     57
Name: count, dtype: int64

In [ ]:
df_clean = df_colcancer[
    (df_colcancer['mucin_type'] != 9) &
    (df_colcancer['cell_diff'] != 9) &
    (df_colcancer['signet_ring'] != 9)  &
    (df_colcancer['lymphovascularinvasion'] != 9) &
    (df_colcancer['perineural'] != 9)
]
df_clean

,bian_ma,age,gender,asa,asa3,dm,cad,hf,cva,ckd,...,signet_ring,lymphovascularinvasion,perineural,ct,rt,nactrt,interval,progress,interval_r,death
0,2,52,1,3,1,0,0,0,0,0,...,0,1,0,1,0,0,11.761807,1,9.856263,1
1,21,85,2,2,0,0,1,0,0,0,...,0,0,0,1,0,0,8.377823,1,7.063655,1
2,22,45,2,2,0,0,0,0,0,0,...,0,1,0,1,0,0,4.763860,1,2.792608,1
3,23,57,2,2,0,0,0,0,0,0,...,0,1,0,1,0,0,2.595483,1,1.774127,1
4,29,43,1,2,0,1,0,0,0,0,...,0,0,0,1,0,0,16.164271,1,7.096509,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,5158,48,1,3,1,0,0,0,0,0,...,0,0,0,1,0,0,18.398357,0,18.398357,0
995,5162,86,1,3,1,0,0,0,0,0,...,0,0,0,0,0,1,17.478439,1,8.410678,0
996,5168,49,2,2,0,0,0,0,0,0,...,0,1,1,0,0,0,0.131417,0,0.131417,0
997,5171,76,2,2,0,1,0,0,0,0,...,0,1,1,1,0,0,20.008214,1,16.558522,0
998,5172,65,1,2,0,0,0,0,0,0,...,0,1,0,1,0,0,19.909651,1,3.909651,0

In [ ]:
#Pre-processing

#number of rows and columns
print(f"Shape dataset:\n {df_clean.shape}")

#variable types
print(f"Data types:\n {df_clean.dtypes}")

#summary statistics
print(f"Summary statistics:\n {df_clean.describe()}")

#distribution of the target variable
print(f"Distribution of the target:\n {df_clean['death'].value_counts()}")

#missing values
print(f"Missing values per column:\n {df_clean.isnull().sum()}")

Shape dataset:
 (931, 31)
Data types:
 bian_ma                     int64
age                         int64
gender                      int64
asa                         int64
asa3                        int64
dm                          int64
cad                         int64
hf                          int64
cva                         int64
ckd                         int64
log_cea                   float64
laparoscopic                int64
tumor_loc                   int64
ea                          int64
anes_time                   int64
log2at                    float64
rbc                         int64
ajcc                        int64
liver_only                  int64
cell_diff                   int64
mucin_type                  int64
signet_ring                 int64
lymphovascularinvasion      int64
perineural                  int64
ct                          int64
rt                          int64
nactrt                      int64
interval                  float64
progress                    int64
interval_r                float64
death                       int64
dtype: object
Summary statistics:
            bian_ma         age      gender         asa        asa3  \
count   931.000000  931.000000  931.000000  931.000000  931.000000
mean   2594.715360   65.324382    1.380236    2.345865    0.380236
std    1502.292168   13.610639    0.485706    0.610510    0.485706
min       2.000000   18.000000    1.000000    1.000000    0.000000
25%    1360.000000   55.000000    1.000000    2.000000    0.000000
50%    2538.000000   65.000000    1.000000    2.000000    0.000000
75%    3964.500000   77.000000    2.000000    3.000000    1.000000
max    5172.000000   95.000000    2.000000    4.000000    1.000000

               dm         cad          hf         cva         ckd  ...  \
count  931.000000  931.000000  931.000000  931.000000  931.000000  ...
mean     0.208378    0.073040    0.044039    0.058002    0.135338  ...
std      0.406367    0.260342    0.205291    0.233873    0.342268  ...
min      0.000000    0.000000    0.000000    0.000000    0.000000  ...
25%      0.000000    0.000000    0.000000    0.000000    0.000000  ...
50%      0.000000    0.000000    0.000000    0.000000    0.000000  ...
75%      0.000000    0.000000    0.000000    0.000000    0.000000  ...
max      1.000000    1.000000    1.000000    1.000000    1.000000  ...

       signet_ring  lymphovascularinvasion  perineural          ct  \
count   931.000000              931.000000  931.000000  931.000000
mean      0.045113                0.514501    0.222342    0.894737
std       0.207663                0.500058    0.416043    0.307057
min       0.000000                0.000000    0.000000    0.000000
25%       0.000000                0.000000    0.000000    1.000000
50%       0.000000                1.000000    0.000000    1.000000
75%       0.000000                1.000000    0.000000    1.000000
max       1.000000                1.000000    1.000000    1.000000

               rt      nactrt    interval    progress  interval_r       death
count  931.000000  931.000000  931.000000  931.000000  931.000000  931.000000
mean     0.107411    0.154672   24.519509    0.785177   11.316881    0.419979
std      0.309802    0.361786   24.284916    0.410920   17.135504    0.493820
min      0.000000    0.000000    0.032854    0.000000    0.032854    0.000000
25%      0.000000    0.000000    7.852156    1.000000    3.039014    0.000000
50%      0.000000    0.000000   17.839836    1.000000    5.946612    0.000000
75%      0.000000    0.000000   31.917864    1.000000   12.599589    1.000000
max      1.000000    1.000000  135.786448    1.000000  134.209446    1.000000

[8 rows x 31 columns]
Distribution of the target:
 death
0    540
1    391
Name: count, dtype: int64
Missing values per column:
 bian_ma                   0
age                       0
gender                    0
asa                       0
asa3                      0
dm                        0
cad                       0
hf                        0
cva                       0
ckd                       0
log_cea                   0
laparoscopic              0
tumor_loc                 0
ea                        0
anes_time                 0
log2at                    0
rbc                       0
ajcc                      0
liver_only                0
cell_diff                 0
mucin_type                0
signet_ring               0
lymphovascularinvasion    0
perineural                0
ct                        0
rt                        0
nactrt                    0
interval                  0
progress                  0
interval_r                0
death                     0
dtype: int64

In [ ]:
#Standard code

X = df_clean.drop(columns=['death'])
y = df_clean['death']

np.random.seed(42)

mcc_vector = []

tracker_standard = EmissionsTracker(
    log_level="error",
    save_to_file=False
)

tracker_standard.start()

start_time_standard = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_standard = RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        class_weight='balanced',
        random_state=42
    )

    rf_standard.fit(
        X_train,
        y_train
    )

    y_pred_standard = rf_standard.predict(
        X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_standard
    )

    mcc_vector.append(mcc)

end_time_standard = time.time()

execution_time_standard = (end_time_standard - start_time_standard)

emissions_standard = tracker_standard.stop() * 1000

energy_standard_wh = (tracker_standard._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_standard_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_standard:.20f}  CO2 eq grams")
print(f"Execution time: {execution_time_standard:.20f} seconds")

The final results are:
Mean MCC: 0.22116466611985494128
Median MCC: 0.22517502749427431574
Standard deviation MCC: 0.05099781197213792278
Minimum MCC: 0.05185485539500656049
Maximum MCC: 0.33296064306819689316

Energy: 0.19842633005044835182 Wh
CO2 emissions: 0.05665145899948071523  CO2 eq grams
Execution time: 44.09179878234863281250 seconds

In [ ]:
#Green code

X = df_clean.drop(columns=['death'])
y = df_clean['death']

np.random.seed(42)

mcc_vector = []

tracker_green = EmissionsTracker(
    log_level="error",
    save_to_file=False)

tracker_green.start()

start_time_green = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_green = RandomForestClassifier(
        n_estimators=20,
        max_depth=5,
        min_samples_leaf=3,
        class_weight='balanced',
        random_state=42
    )

    rf_green.fit(
        X_train,
        y_train
    )

    y_pred_green = rf_green.predict(
        X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_green
    )

    mcc_vector.append(mcc)

end_time_green = time.time()

execution_time_green = (end_time_green - start_time_green)

emissions_green = tracker_green.stop() * 1000

energy_green_wh = (tracker_green._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_green_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_green:.20f} CO2 eq grams")
print(f"Execution time: {execution_time_green:.20f} seconds")

The final results are:
Mean MCC: 0.25237408305332154068
Median MCC: 0.24999284143240160794
Standard deviation MCC: 0.05626590644955356546
Minimum MCC: 0.07232717276712437304
Maximum MCC: 0.38845923161818174396

Energy: 0.01937262758913455007 Wh
CO2 emissions: 0.00553095759670118974 CO2 eq grams
Execution time: 5.07690572738647460938 seconds

# Fourth Dataset: Depression heart failure

In [ ]:
df_dep_heart_failure = pd.read_csv("/content/depression_heart_failure.csv")
df_dep_heart_failure = df_dep_heart_failure.rename(columns={"Death (1=Yes, 0=No)": "Death"})
df_dep_heart_failure

,Age (years),"Male (1=Yes, 0=No)",PHQ-9,Systolic BP (mm Hg),Estimated glomerular filtration rate,Ejection fraction (%),Serum sodium (mmol/l),Blood urea nitrogen (mg/dl),"Etiology HF(1=Yes, 0=No)",Prior diabetes mellitus,"Elevated level of BNP/NT-BNP (1=Yes, 0=No)",Time from HF to Death (days),Time from HF to hospitalization (days),"Hospitalized (1=Yes, 0=No)",Death
0,93,0,1,145.0,46.352457,60.50,137,26,1,1,1,679,134,1,1
1,99,1,8,115.0,32.827851,65.00,140,75,1,0,1,74,74,0,1
2,83,1,4,121.0,57.821591,65.00,141,28,0,0,1,730,224,1,0
3,86,1,4,113.0,63.469884,32.50,141,47,0,1,1,730,5,1,0
4,84,1,3,142.0,57.681188,58.00,137,32,0,1,1,730,730,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,50,1,3,143.0,79.094655,49.50,137,27,1,1,1,730,156,1,0
421,73,1,11,155.0,29.486806,58.00,139,42,0,0,1,730,730,0,0
422,63,1,17,135.0,113.901326,27.40,130,17,0,1,1,338,338,0,1
423,48,1,4,172.0,58.919011,16.83,140,34,0,0,1,730,730,0,0
424,54,0,25,134.0,40.644046,55.00,141,77,0,1,1,694,9,1,1

In [ ]:
#Pre-processing

#number of rows and columns
print(f"Shape dataset:\n {df_dep_heart_failure.shape}")

#variable types
print(f"Data types:\n {df_dep_heart_failure.dtypes}")

#summary statistics
print(f"Summary statistics:\n  {df_dep_heart_failure.describe()}")

#distribution of target variable
print(f"Distribution target:\n {df_dep_heart_failure["Death"].value_counts()}")

#missing values
print(f"Missing values per column:\n {df_dep_heart_failure.isnull().sum()}")

Shape dataset:
 (425, 15)
Data types:
 Age (years)                                     int64
Male (1=Yes, 0=No)                              int64
PHQ-9                                           int64
Systolic BP (mm Hg)                           float64
Estimated glomerular filtration rate          float64
Ejection fraction (%)                         float64
Serum sodium (mmol/l)                           int64
Blood urea nitrogen (mg/dl)                     int64
Etiology HF(1=Yes, 0=No)                        int64
Prior diabetes mellitus                         int64
Elevated level of BNP/NT-BNP (1=Yes, 0=No)      int64
Time from HF to Death (days)                    int64
Time from HF to hospitalization (days)          int64
Hospitalized (1=Yes, 0=No)                      int64
Death                                           int64
dtype: object
Summary statistics:
         Age (years)  Male (1=Yes, 0=No)       PHQ-9  Systolic BP (mm Hg)  \
count   425.000000          425.000000  425.000000           425.000000
mean     73.517647            0.576471    4.774118           123.911765
std      13.153674            0.494700    4.809659            23.062259
min      21.000000            0.000000    0.000000            64.000000
25%      65.000000            0.000000    1.000000           108.000000
50%      76.000000            1.000000    4.000000           122.000000
75%      84.000000            1.000000    7.000000           139.000000
max      99.000000            1.000000   25.000000           214.000000

       Estimated glomerular filtration rate  Ejection fraction (%)  \
count                            425.000000             425.000000
mean                              57.117512              45.956179
std                               22.972793              16.411982
min                                5.539146              11.500000
25%                               43.116583              32.000000
50%                               55.754675              49.000000
75%                               71.537513              60.000000
max                              166.363958              82.000000

       Serum sodium (mmol/l)  Blood urea nitrogen (mg/dl)  \
count             425.000000                   425.000000
mean              139.148235                    29.287059
std                 3.315082                    15.123780
min               126.000000                     0.000000
25%               137.000000                    19.000000
50%               139.000000                    26.000000
75%               141.000000                    36.000000
max               148.000000                   119.000000

       Etiology HF(1=Yes, 0=No)  Prior diabetes mellitus  \
count                425.000000               425.000000
mean                   0.425882                 0.383529
std                    0.495059                 0.486818
min                    0.000000                 0.000000
25%                    0.000000                 0.000000
50%                    0.000000                 0.000000
75%                    1.000000                 1.000000
max                    1.000000                 1.000000

       Elevated level of BNP/NT-BNP (1=Yes, 0=No)  \
count                                  425.000000
mean                                     0.712941
std                                      0.452922
min                                      0.000000
25%                                      0.000000
50%                                      1.000000
75%                                      1.000000
max                                      1.000000

       Time from HF to Death (days)  Time from HF to hospitalization (days)  \
count                    425.000000                              425.000000
mean                     641.543529                              330.376471
std                      187.110813                              285.389810
min                        5.000000                                1.000000
25%                      730.000000                               69.000000
50%                      730.000000                              229.000000
75%                      730.000000                              730.000000
max                      730.000000                              730.000000

       Hospitalized (1=Yes, 0=No)       Death
count                  425.000000  425.000000
mean                     0.703529    0.232941
std                      0.457239    0.423203
min                      0.000000    0.000000
25%                      0.000000    0.000000
50%                      1.000000    0.000000
75%                      1.000000    0.000000
max                      1.000000    1.000000
Distribution target:
 Death
0    326
1     99
Name: count, dtype: int64
Missing values per column:
 Age (years)                                   0
Male (1=Yes, 0=No)                            0
PHQ-9                                         0
Systolic BP (mm Hg)                           0
Estimated glomerular filtration rate          0
Ejection fraction (%)                         0
Serum sodium (mmol/l)                         0
Blood urea nitrogen (mg/dl)                   0
Etiology HF(1=Yes, 0=No)                      0
Prior diabetes mellitus                       0
Elevated level of BNP/NT-BNP (1=Yes, 0=No)    0
Time from HF to Death (days)                  0
Time from HF to hospitalization (days)        0
Hospitalized (1=Yes, 0=No)                    0
Death                                         0
dtype: int64

In [ ]:
#correlation coefficient
df_dep_heart_failure.corr()["Death"].sort_values()

Time from HF to Death (days)                 -0.858882
Time from HF to hospitalization (days)       -0.304771
Estimated glomerular filtration rate         -0.290426
Systolic BP (mm Hg)                          -0.110014
Male (1=Yes, 0=No)                           -0.045856
Serum sodium (mmol/l)                        -0.019627
Ejection fraction (%)                        -0.002139
Prior diabetes mellitus                       0.057589
Etiology HF(1=Yes, 0=No)                      0.110744
Elevated level of BNP/NT-BNP (1=Yes, 0=No)    0.128198
Hospitalized (1=Yes, 0=No)                    0.138344
PHQ-9                                         0.200875
Age (years)                                   0.231225
Blood urea nitrogen (mg/dl)                   0.279160
Death                                         1.000000
Name: Death, dtype: float64

In [ ]:
#Standard code

X = df_dep_heart_failure.drop(columns=["Death", "Time from HF to Death (days)", "Time from HF to hospitalization (days)"])
y = df_dep_heart_failure["Death"]

np.random.seed(42)

mcc_vector = []

tracker_standard = EmissionsTracker(
    log_level="error",
    save_to_file=False)

tracker_standard.start()

start_time_standard = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_standard = RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        class_weight='balanced',
        random_state=42
    )

    rf_standard.fit(
        X_train,
        y_train
    )

    y_pred_standard = rf_standard.predict(
        X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_standard
    )
    mcc_vector.append(mcc)

end_time_standard = time.time()

execution_time_standard = (end_time_standard - start_time_standard)

emissions_standard = tracker_standard.stop() * 1000

energy_standard_wh = (tracker_standard._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_standard_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_standard:.20f}  CO2 eq grams")
print(f"Execution time: {execution_time_standard:.20f} seconds")

The final results are:
Mean MCC: 0.25341165174562874096
Median MCC: 0.25126452936094562096
Standard deviation MCC: 0.08968759564987312249
Minimum MCC: 0.02915026191924190158
Maximum MCC: 0.45743029704172155636

Energy: 0.17898474893835511490 Wh
CO2 emissions: 0.05110081491420832150  CO2 eq grams
Execution time: 30.20840549468994140625 seconds

In [ ]:
#Green code

X = df_dep_heart_failure.drop(columns=["Death", "Time from HF to Death (days)", "Time from HF to hospitalization (days)"])
y = df_dep_heart_failure["Death"]

np.random.seed(42)

mcc_vector = []

tracker_green = EmissionsTracker(
    log_level="error",
    save_to_file=False)

tracker_green.start()

start_time_green = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_green = RandomForestClassifier(
        n_estimators=20,
        max_depth=5,
        min_samples_leaf=3,
        class_weight='balanced',
        random_state=42
    )

    rf_green.fit(
        X_train,
        y_train)

    y_pred_green = rf_green.predict(
        X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_green
    )

    mcc_vector.append(mcc)

end_time_green = time.time()

execution_time_green = (end_time_green - start_time_green)

emissions_green = tracker_green.stop() * 1000

energy_green_wh = (tracker_green._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.4f}")
print(f"Median MCC: {np.median(mcc_vector):.4f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.4f}")
print(f"Minimum MCC: {np.min(mcc_vector):.4f}")
print(f"Maximum MCC: {np.max(mcc_vector):.4f}")
print(f"\nEnergy: {energy_green_wh:.6f} Wh")
print(f"CO2 emissions: {emissions_green:.6f} CO2 eq grams")
print(f"Execution time: {execution_time_green:.4f} seconds")

The final results are:
Mean MCC: 0.3343
Median MCC: 0.3338
Standard deviation MCC: 0.0868
Minimum MCC: 0.1266
Maximum MCC: 0.5482

Energy: 0.016747 Wh
CO2 emissions: 0.004781 CO2 eq grams
Execution time: 4.2695 seconds

# Fifth Dataset: Sepsis

In [ ]:
df_sepsis = pd.read_csv("/content/journal_Text_Sepsis.csv")
df_sepsis

,Age,sex_woman,diagnosis_0EC_1M_2_AC,APACHE II,SOFA,CRP,WBCC,NeuC,LymC,EOC,NLCR,PLTC,MPV,Group,LOS-ICU,Mortality
0,23,0,2,14,0,0.02,10.48,8.66,1.22,40,7.1,176,10.0,0,1,0
1,53,0,2,10,3,9.00,19.16,16.28,0.62,0,26.3,280,10.8,0,1,0
2,83,0,2,8,4,11.91,12.60,9.91,0.72,0,13.8,98,9.2,0,1,0
3,35,0,2,3,0,7.38,7.70,5.97,0.94,20,6.4,254,7.9,0,1,0
4,86,0,2,17,2,4.97,10.64,9.73,0.78,0,12.5,133,11.8,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1252,84,1,1,18,3,0.30,6.71,5.26,0.81,30,6.5,145,9.7,0,6,0
1253,30,1,1,3,0,0.10,7.89,3.43,3.47,30,1.0,268,10.3,0,1,0
1254,62,1,1,19,6,4.50,4.49,3.53,0.31,20,11.4,188,8.6,0,15,0
1255,31,1,1,16,5,2.00,8.40,6.69,0.76,20,8.8,164,9.0,1,4,0
1256,50,0,1,5,1,6.53,11.58,9.87,0.90,0,11.0,191,9.6,0,1,0

In [ ]:
#Pre-processing

#number of rows and columns
print(f"Shape dataset:\n {df_sepsis.shape}")

#variable types
print(f"Data types:\n {df_sepsis.dtypes}")

#summary statistics
print(f"Summary statistics:\n {df_sepsis.describe()}")

#distribution of target variable
print(f"Distribution of the target:\n {df_sepsis["Mortality"].value_counts()}")

#missing values
print(f"Missing values per column:\n {df_sepsis.isnull().sum()}")

Shape dataset:
 (1257, 16)
Data types:
 Age                        int64
sex_woman                  int64
diagnosis_0EC_1M_2_AC      int64
APACHE II                  int64
SOFA                       int64
CRP                      float64
WBCC                     float64
NeuC                     float64
LymC                     float64
EOC                        int64
NLCR                     float64
PLTC                       int64
MPV                      float64
Group                      int64
LOS-ICU                    int64
Mortality                  int64
dtype: object
Summary statistics:
                Age    sex_woman  diagnosis_0EC_1M_2_AC    APACHE II  \
count  1257.000000  1257.000000            1257.000000  1257.000000
mean     56.505967     0.408115               0.546539    13.336516
std      19.235512     0.491680               0.566816     8.209763
min      18.000000     0.000000               0.000000     0.000000
25%      41.000000     0.000000               0.000000     7.000000
50%      58.000000     0.000000               1.000000    11.000000
75%      71.000000     1.000000               1.000000    18.000000
max      99.000000     1.000000               2.000000    48.000000

              SOFA          CRP         WBCC         NeuC         LymC  \
count  1257.000000  1257.000000  1257.000000  1257.000000  1257.000000
mean      2.582339     6.185084    11.767942     9.900497     1.034519
std       3.253823     8.241324     5.962340     5.338879     0.755753
min       0.000000     0.000000     0.600000     0.200000     0.005000
25%       0.000000     0.700000     7.740000     6.190000     0.550000
50%       1.000000     3.000000    10.790000     9.020000     0.860000
75%       4.000000     8.000000    14.890000    12.730000     1.280000
max      16.000000    52.050000    51.080000    50.500000     6.970000

               EOC         NLCR         PLTC          MPV        Group  \
count  1257.000000  1257.000000  1257.000000  1257.000000  1257.000000
mean     27.239459    13.116627   194.361973    10.127741     0.350835
std      42.282799    15.289847   107.593931     3.722421     0.477421
min       0.000000     0.500000    11.000000     0.000000     0.000000
25%       0.000000     6.900000   120.000000     9.400000     0.000000
50%      10.000000    10.500000   184.000000    10.000000     0.000000
75%      40.000000    15.500000   247.000000    10.800000     1.000000
max     410.000000   420.800000   854.000000   107.000000     1.000000

           LOS-ICU    Mortality
count  1257.000000  1257.000000
mean      4.435959     0.102625
std       8.526331     0.303590
min       1.000000     0.000000
25%       1.000000     0.000000
50%       1.000000     0.000000
75%       4.000000     0.000000
max      96.000000     1.000000
Distribution of the target:
 Mortality
0    1128
1     129
Name: count, dtype: int64
Missing values per column:
 Age                      0
sex_woman                0
diagnosis_0EC_1M_2_AC    0
APACHE II                0
SOFA                     0
CRP                      0
WBCC                     0
NeuC                     0
LymC                     0
EOC                      0
NLCR                     0
PLTC                     0
MPV                      0
Group                    0
LOS-ICU                  0
Mortality                0
dtype: int64

In [ ]:
#Standard code

X = df_sepsis.drop(columns=['Mortality'])
y = df_sepsis['Mortality']

np.random.seed(42)

mcc_vector = []

tracker_standard = EmissionsTracker(
    log_level="error",
    save_to_file=False
)

tracker_standard.start()

start_time_standard = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_standard = RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        class_weight='balanced',
        random_state=42
    )

    rf_standard.fit(
        X_train,
        y_train
    )

    y_pred_standard = rf_standard.predict(
        X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_standard
    )

    mcc_vector.append(mcc)

end_time_standard = time.time()

execution_time_standard = (end_time_standard - start_time_standard)

emissions_standard = tracker_standard.stop() * 1000

energy_standard_wh = (tracker_standard._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_standard_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_standard:.20f} CO2 eq grams")
print(f"Execution time: {execution_time_standard:.20f} seconds")

The final results are:
Mean MCC: 0.49551891613907378398
Median MCC: 0.49577120947674374607
Standard deviation MCC: 0.06319988792079596351
Minimum MCC: 0.38604410036067665635
Maximum MCC: 0.64129752839129172681

Energy: 0.16180171713010391144 Wh
CO2 emissions: 0.04619499509823719180 CO2 eq grams
Execution time: 37.04455256462097167969 seconds

In [ ]:
#Green code

X = df_sepsis.drop(columns=['Mortality'])
y = df_sepsis['Mortality']

np.random.seed(42)

mcc_vector = []

tracker_green = EmissionsTracker(
    log_level="error",
    save_to_file=False
)

tracker_green.start()

start_time_green = time.time()

for i in range(100):
    #train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        random_state=i
    )

    #Random Forest
    rf_green = RandomForestClassifier(
        n_estimators=20,
        max_depth=5,
        min_samples_leaf=3,
        class_weight='balanced',
        random_state=42
    )

    rf_green.fit(
        X_train,
        y_train
    )

    y_pred_green = rf_green.predict(
        X_test)

    #MCC
    mcc = matthews_corrcoef(
        y_test,
        y_pred_green)

    mcc_vector.append(mcc)

end_time_green = time.time()

execution_time_green = (end_time_green - start_time_green)

emissions_green = tracker_green.stop() * 1000

energy_green_wh = (tracker_green._total_energy.kWh * 1000)

print("The final results are:")

print(f"Mean MCC: {np.mean(mcc_vector):.20f}")
print(f"Median MCC: {np.median(mcc_vector):.20f}")
print(f"Standard deviation MCC: {np.std(mcc_vector):.20f}")
print(f"Minimum MCC: {np.min(mcc_vector):.20f}")
print(f"Maximum MCC: {np.max(mcc_vector):.20f}")
print(f"\nEnergy: {energy_green_wh:.20f} Wh")
print(f"CO2 emissions: {emissions_green:.20f} CO2 eq grams")
print(f"Execution time: {execution_time_green:.20f} seconds")

The final results are:
Mean MCC: 0.58093971236008401515
Median MCC: 0.58617846343864810077
Standard deviation MCC: 0.04893989227278711107
Minimum MCC: 0.45199166799462980881
Maximum MCC: 0.69820413248459489708

Energy: 0.04594324608138774385 Wh
CO2 emissions: 0.01311696850423560955 CO2 eq grams
Execution time: 8.97203373908996582031 seconds